### ISSUE TITLE
关于新的代码托管平台技术选型的讨论

### ISSUE THREAD

**Issue by fcharlie** [growerlab/draft#1]
WIP

@molizz 
@auguszou
@chanhx

**Comment by molizz** [comment]
1. 前端 react
2. 后端 golang + gin + mysql
3. 缓存 redis
暂定？

**Comment by fcharlie** [comment]
@molizz 我觉得无论是 MariaDB 还是 PostgreSQL 都可能比 MySQL 要好一些。

redis 的话，有一个协议兼容的 KeyDB 替代方案（KeyDB 是多线程实现。）

**Comment by molizz** [comment]
> @molizz 我觉得无论是 MariaDB 还是 PostgreSQL 都可能比 MySQL 要好一些。
> 
> redis 的话，有一个协议兼容的 KeyDB 替代方案（KeyDB 是多线程实现。）

pgsql是不错的，我觉得也是可以的。 KeyDB 也不错呀

**Comment by molizz** [comment]
所以暂定
数据库 pgsql， 缓存 keyDB

**Comment by molizz** [comment]
react的ui库确认用 ant

**Comment by molizz** [comment]
react 使用 typescript 语言

**Comment by fcharlie** [comment]
接入发散，图一：

![image](https://user-images.githubusercontent.com/6904176/67611109-dffe8f80-f7c9-11e9-8ee5-4a76fb9df26d.png)

未完待续
